version: 0.2
phases:
  pre_build:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
      - mv build ../backend/
      - cd ../backend
      - npm install
      - npm shrinkwrap
  post_build:
    commands:
      - npm run buildpack
