---
phases:
  build:
    commands:
      - cd frontend
      - npm install
      - npm run build
      - mv build ../backend/
      - cd ../backend
      - npm install
      - npm shrinkwrap
      # - npm run buildpack
