version: 0.2
phases:
  pre_build:
    commands:
      - npm install -g npm@latest
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
      - mv build ../backend/
      - cd ../backend
      - npm install
      - npm shrinkwrap
  post_build:
    commands:
      - cd ..
      - zip -r maintain.zip backend/
artifacts:
  files:
    - maintain.zip
